; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:esp32s3_n16r8]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino

upload_protocol = esp-builtin ; Use the built-in USB-JTAG for uploading
debug_tool = esp-builtin      ; Use the built-in USB-JTAG for debugging
build_type = debug            ; Enable debug build type

; --- USB CDC Configuration ---
; Route Serial data to the native USB CDC port
build_flags = 
    -D ARDUINO_USB_CDC_ON_BOOT=1 
    -D ARDUINO_USB_MODE=1 ; Use Hardware CDC and JTAG mode

board_build.f_cpu = 240000000L
board_build.flash_mode = qio
board_build.flash_size = 16MB

board_build.psram_type = qspi
; board_build.arduino.memory_type = opi_opi

lib_deps = bblanchon/ArduinoJson @ ^6.21.3

build_src_filter = +<*> -<backup_*>

; [env:bpi_leaf_s3]
; platform = espressif32
; board = bpi_leaf_s3
; framework = arduino
; board_build.f_cpu = 240000000L
; build_flags = -DARDUINO_ENABLE_PSRAM=0
; lib_deps = bblanchon/ArduinoJson@^6.21.3
; build_src_filter = +<*> -<backup_*>

extra_scripts = pre:extra_script.py